name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master  # Adjust this to your default branch
    paths:
      - 'backend/**'  # Only trigger on changes in the 'backend' subfolder

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust this as needed

      - name: Build and tag Docker image
        working-directory: backend  # Navigate to the 'backend' subfolder
        run: |
          docker build -t backend-api .
          docker tag backend-api madman98/0x9stellervoyage:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Push Docker image
        run: docker push madman98/0x9stellervoyage:latest

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLETIP }}
          username: ${{ secrets.DROPLETSSHUSER }}
          key: ${{ secrets.SSHPRIVATEKEY }}
          script: |
            docker stop backend-api || true
            docker rm backend-api || true
            docker pull madman98/0x9stellervoyage:latest
            docker run -d -p 8080:8080 --name madman98/0x9stellervoyage:latest
